# Generated by Django 4.0.3 on 2023-07-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_review_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
