"""empty message

Revision ID: 123530a29485
Revises: 19a455ba0298
Create Date: 2023-07-18 11:07:15.246844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "123530a29485"
down_revision = "19a455ba0298"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attribute", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.execute("UPDATE attribute SET deleted = false WHERE deleted is NULL")
    op.alter_column("attribute", "deleted", nullable=False)

    op.add_column(
        "attribute_product_variant", sa.Column("deleted", sa.Boolean(), nullable=True)
    )
    op.execute(
        "UPDATE attribute_product_variant SET deleted = false WHERE deleted is NULL"
    )
    op.alter_column("attribute_product_variant", "deleted", nullable=False)

    op.add_column("attribute_type", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.execute("UPDATE attribute_type SET deleted = false WHERE deleted is NULL")
    op.alter_column("attribute_type", "deleted", nullable=False)

    op.add_column(
        "attribute_type_product_type",
        sa.Column("deleted", sa.Boolean(), nullable=True),
    )
    op.execute(
        "UPDATE attribute_type_product_type SET deleted = false WHERE deleted is NULL"
    )
    op.alter_column("attribute_type_product_type", "deleted", nullable=False)

    op.add_column(
        "category_ancestor", sa.Column("deleted", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE category_ancestor SET deleted = false WHERE deleted is NULL")
    op.alter_column("category_ancestor", "deleted", nullable=False)

    op.add_column("order", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.execute('UPDATE "order" SET deleted = false WHERE deleted is NULL')
    op.alter_column("order", "deleted", nullable=False)

    op.add_column(
        "order_product_variant", sa.Column("deleted", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE order_product_variant SET deleted = false WHERE deleted is NULL")
    op.alter_column("order_product_variant", "deleted", nullable=False)

    op.add_column("product", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.execute("UPDATE product SET deleted = false WHERE deleted is NULL")
    op.alter_column("product", "deleted", nullable=False)

    op.add_column("product_price", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.execute("UPDATE product_price SET deleted = false WHERE deleted is NULL")
    op.alter_column("product_price", "deleted", nullable=False)

    op.add_column(
        "product_product_variant", sa.Column("deleted", sa.Boolean(), nullable=True)
    )
    op.execute(
        "UPDATE product_product_variant SET deleted = false WHERE deleted is NULL"
    )
    op.alter_column("product_product_variant", "deleted", nullable=False)

    op.add_column(
        "product_translation", sa.Column("deleted", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE product_translation SET deleted = false WHERE deleted is NULL")
    op.alter_column("product_translation", "deleted", nullable=False)

    op.add_column("product_type", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.execute("UPDATE product_type SET deleted = false WHERE deleted is NULL")
    op.alter_column("product_type", "deleted", nullable=False)

    op.add_column("product_variant", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.execute("UPDATE product_variant SET deleted = false WHERE deleted is NULL")
    op.alter_column("product_variant", "deleted", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_variant", "deleted")
    op.drop_column("product_type", "deleted")
    op.drop_column("product_translation", "deleted")
    op.drop_column("product_product_variant", "deleted")
    op.drop_column("product_price", "deleted")
    op.drop_column("product", "deleted")
    op.drop_column("order_product_variant", "deleted")
    op.drop_column("order", "deleted")
    op.drop_column("category_ancestor", "deleted")
    op.drop_column("attribute_type_product_type", "deleted")
    op.drop_column("attribute_type", "deleted")
    op.drop_column("attribute_product_variant", "deleted")
    op.drop_column("attribute", "deleted")
    # ### end Alembic commands ###
