"""empty message

Revision ID: 19a455ba0298
Revises: 562a8029eacb
Create Date: 2023-07-02 22:53:11.933128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "19a455ba0298"
down_revision = "562a8029eacb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("token", sa.UUID(), nullable=False),
        sa.Column("update_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("create_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_table(
        "order_product_variant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("order_token", sa.UUID(), nullable=False),
        sa.Column("product_variant_sku", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_product_variant")
    op.drop_table("order")
    # ### end Alembic commands ###
