"""empty message

Revision ID: 36d6eacc5123
Revises: ab41ebeacee6
Create Date: 2023-05-02 22:50:00.945241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36d6eacc5123"
down_revision = "ab41ebeacee6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("attribute", "value", new_column_name="raw_value")
    op.add_column("attribute", sa.Column("numeric_value", sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("attribute", "raw_value", new_column_name="value")
    op.drop_column("attribute", "numeric_value")
    # ### end Alembic commands ###
