"""empty message

Revision ID: 562a8029eacb
Revises: 2c77bcef818e
Create Date: 2023-07-02 22:52:51.052297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "562a8029eacb"
down_revision = "2c77bcef818e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_product_variant")
    op.drop_table("order")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "update_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "create_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "session_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="order_pkey"),
    )
    op.create_table(
        "order_product_variant",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("order_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "product_variant_sku",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="order_product_variant_pkey"),
    )
    # ### end Alembic commands ###
