"""empty message

Revision ID: d831e431c5a3
Revises: e1aea32efeb2
Create Date: 2023-04-22 19:23:23.619799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd831e431c5a3'
down_revision = 'e1aea32efeb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attribute_attribute_type_id_fkey', 'attribute', type_='foreignkey')
    op.drop_constraint('attribute_parent_attribute_id_fkey', 'attribute', type_='foreignkey')
    op.drop_constraint('attribute_product_variant_product_variant_sku_fkey', 'attribute_product_variant', type_='foreignkey')
    op.drop_constraint('attribute_product_variant_attribute_id_fkey', 'attribute_product_variant', type_='foreignkey')
    op.drop_constraint('attribute_type_product_type_product_type_id_fkey', 'attribute_type_product_type', type_='foreignkey')
    op.drop_constraint('attribute_type_product_type_attribute_type_id_fkey', 'attribute_type_product_type', type_='foreignkey')
    op.drop_constraint('product_product_type_id_fkey', 'product', type_='foreignkey')
    op.drop_constraint('product_product_variant_product_variant_sku_fkey', 'product_product_variant', type_='foreignkey')
    op.drop_constraint('product_product_variant_product_id_fkey', 'product_product_variant', type_='foreignkey')
    op.drop_constraint('product_translation_product_id_fkey', 'product_translation', type_='foreignkey')
    op.drop_constraint('product_variant_product_id_fkey', 'product_variant', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('product_variant_product_id_fkey', 'product_variant', 'product', ['product_id'], ['id'])
    op.create_foreign_key('product_translation_product_id_fkey', 'product_translation', 'product', ['product_id'], ['id'])
    op.create_foreign_key('product_product_variant_product_id_fkey', 'product_product_variant', 'product', ['product_id'], ['id'])
    op.create_foreign_key('product_product_variant_product_variant_sku_fkey', 'product_product_variant', 'product_variant', ['product_variant_sku'], ['sku'])
    op.create_foreign_key('product_product_type_id_fkey', 'product', 'product_type', ['product_type_id'], ['id'])
    op.create_foreign_key('attribute_type_product_type_attribute_type_id_fkey', 'attribute_type_product_type', 'attribute_type', ['attribute_type_id'], ['id'])
    op.create_foreign_key('attribute_type_product_type_product_type_id_fkey', 'attribute_type_product_type', 'product_type', ['product_type_id'], ['id'])
    op.create_foreign_key('attribute_product_variant_attribute_id_fkey', 'attribute_product_variant', 'attribute', ['attribute_id'], ['id'])
    op.create_foreign_key('attribute_product_variant_product_variant_sku_fkey', 'attribute_product_variant', 'product_variant', ['product_variant_sku'], ['sku'])
    op.create_foreign_key('attribute_parent_attribute_id_fkey', 'attribute', 'attribute', ['parent_attribute_id'], ['id'])
    op.create_foreign_key('attribute_attribute_type_id_fkey', 'attribute', 'attribute_type', ['attribute_type_id'], ['id'])
    # ### end Alembic commands ###
