"""empty message

Revision ID: e872d1f2d291
Revises: e1aea32efeb2
Create Date: 2023-04-22 15:03:18.495060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e872d1f2d291"
down_revision = "e1aea32efeb2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_price",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("price_list_code", sa.String(length=200), nullable=True),
        sa.Column("price", sa.DECIMAL(), nullable=True),
        sa.Column("update_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("create_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("product_variant_sku", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_variant_sku"],
            ["product_variant.sku"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_price")
    # ### end Alembic commands ###
