# Generated by Django 4.0.3 on 2023-07-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managergroup',
            name='safe_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managerpermission',
            name='safe_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
