"""empty message

Revision ID: 094e920c9f4f
Revises: 5cb77fda3ccd
Create Date: 2023-07-18 11:07:21.572802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "094e920c9f4f"
down_revision = "5cb77fda3ccd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("config", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.execute("UPDATE config SET deleted = false WHERE deleted is NULL")
    op.alter_column("config", "deleted", nullable=False)

    op.add_column(
        "latest_identifier", sa.Column("deleted", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE latest_identifier SET deleted = false WHERE deleted is NULL")
    op.alter_column("latest_identifier", "deleted", nullable=False)

    op.add_column("trainer_queue", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.execute("UPDATE trainer_queue SET deleted = false WHERE deleted is NULL")
    op.alter_column("trainer_queue", "deleted", nullable=False)

    op.add_column(
        "training_statistics", sa.Column("deleted", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE training_statistics SET deleted = false WHERE deleted is NULL")
    op.alter_column("training_statistics", "deleted", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("training_statistics", "deleted")
    op.drop_column("trainer_queue", "deleted")
    op.drop_column("latest_identifier", "deleted")
    op.drop_column("config", "deleted")
    # ### end Alembic commands ###
