"""empty message

Revision ID: 19f3cec5576d
Revises: 6e650ff82b22
Create Date: 2023-08-28 09:30:01.947904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "19f3cec5576d"
down_revision = "6e650ff82b22"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_finished",
        sa.Column("training_id", sa.UUID(), nullable=False),
        sa.Column("create_at", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("training_id"),
    )
    op.create_table(
        "training_started",
        sa.Column("training_id", sa.UUID(), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("model_identifier", sa.String(length=255), nullable=False),
        sa.Column("create_at", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("training_id"),
    )
    op.create_table(
        "training_step_finished",
        sa.Column("step_id", sa.UUID(), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("model_identifier", sa.String(length=255), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("create_at", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("step_id"),
    )
    op.create_table(
        "training_step_started",
        sa.Column("step_id", sa.UUID(), nullable=False),
        sa.Column("training_id", sa.UUID(), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("model_identifier", sa.String(length=255), nullable=False),
        sa.Column("hyperparameters", sa.JSON(), nullable=False),
        sa.Column("create_at", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("step_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("training_step_started")
    op.drop_table("training_step_finished")
    op.drop_table("training_started")
    op.drop_table("training_finished")
    # ### end Alembic commands ###
