"""empty message

Revision ID: 2d418d8853cb
Revises: 565d666c571a
Create Date: 2023-07-02 16:04:28.528227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2d418d8853cb"
down_revision = "565d666c571a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("config", sa.Column("ease_config", sa.JSON(), nullable=True))
    op.execute("UPDATE config SET ease_config = '{}'::json WHERE ease_config is NULL")
    op.alter_column("config", "ease_config", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("config", "ease_config")
    # ### end Alembic commands ###
