"""empty message

Revision ID: 52d58040568a
Revises: 0fac02b3d7fe
Create Date: 2023-05-07 23:20:01.264661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52d58040568a"
down_revision = "0fac02b3d7fe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "distance_distance_idx", "trainer_queue", ["create_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("distance_distance_idx", table_name="trainer_queue")
    # ### end Alembic commands ###
