"""empty message

Revision ID: 565d666c571a
Revises: afdac58c6f0f
Create Date: 2023-06-29 12:30:10.960313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "565d666c571a"
down_revision = "afdac58c6f0f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training_statistics", sa.Column("full_train", sa.Boolean(), nullable=True)
    )
    op.execute(
        "UPDATE training_statistics SET full_train = true WHERE full_train is NULL"
    )
    op.alter_column("training_statistics", "full_train", nullable=False)
    op.add_column(
        "training_statistics", sa.Column("create_at", sa.TIMESTAMP(), nullable=True)
    )
    op.execute(
        "UPDATE training_statistics SET create_at = now() WHERE create_at is NULL"
    )
    op.alter_column("training_statistics", "create_at", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("training_statistics", "create_at")
    op.drop_column("training_statistics", "full_train")
    # ### end Alembic commands ###
