"""empty message

Revision ID: 5a3e56bd9283
Revises: 52d58040568a
Create Date: 2023-05-15 23:05:03.351736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5a3e56bd9283"
down_revision = "52d58040568a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("create_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("retrieval_size", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("config")
    # ### end Alembic commands ###
