"""empty message

Revision ID: 5cb77fda3ccd
Revises: 1e21887d01e9
Create Date: 2023-07-08 21:55:22.796639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5cb77fda3ccd"
down_revision = "1e21887d01e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("config", sa.Column("ordering_size", sa.Integer(), nullable=False))
    op.add_column(
        "config",
        sa.Column(
            "homepage_retrieval_cascade",
            postgresql.ARRAY(sa.String(length=255)),
            nullable=False,
        ),
    )
    op.add_column(
        "config",
        sa.Column(
            "homepage_scoring_cascade",
            postgresql.ARRAY(sa.String(length=255)),
            nullable=False,
        ),
    )
    op.add_column(
        "config",
        sa.Column(
            "category_list_scoring_cascade",
            postgresql.ARRAY(sa.String(length=255)),
            nullable=False,
        ),
    )
    op.add_column(
        "config",
        sa.Column(
            "product_detail_retrieval_cascade",
            postgresql.ARRAY(sa.String(length=255)),
            nullable=False,
        ),
    )
    op.add_column(
        "config",
        sa.Column(
            "product_detail_scoring_cascade",
            postgresql.ARRAY(sa.String(length=255)),
            nullable=False,
        ),
    )
    op.add_column(
        "config",
        sa.Column(
            "cart_retrieval_cascade",
            postgresql.ARRAY(sa.String(length=255)),
            nullable=False,
        ),
    )
    op.add_column(
        "config",
        sa.Column(
            "cart_scoring_cascade",
            postgresql.ARRAY(sa.String(length=255)),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("config", "cart_scoring_cascade")
    op.drop_column("config", "cart_retrieval_cascade")
    op.drop_column("config", "product_detail_scoring_cascade")
    op.drop_column("config", "product_detail_retrieval_cascade")
    op.drop_column("config", "category_list_scoring_cascade")
    op.drop_column("config", "homepage_scoring_cascade")
    op.drop_column("config", "homepage_retrieval_cascade")
    op.drop_column("config", "ordering_size")
    # ### end Alembic commands ###
