"""empty message

Revision ID: 6e650ff82b22
Revises: 094e920c9f4f
Create Date: 2023-08-22 10:56:56.198284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e650ff82b22"
down_revision = "094e920c9f4f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("config", sa.Column("models_disabled", sa.JSON(), nullable=True))
    op.execute(
        "UPDATE config SET models_disabled = '{}'::json WHERE models_disabled is NULL"
    )
    op.alter_column("config", "models_disabled", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("config", "models_disabled")
    # ### end Alembic commands ###
