"""empty message

Revision ID: 813aa213bc95
Revises: 5a3e56bd9283
Create Date: 2023-05-15 23:15:34.612365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "813aa213bc95"
down_revision = "5a3e56bd9283"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("config_create_at_idx", "config", ["create_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("config_create_at_idx", table_name="config")
    # ### end Alembic commands ###
