"""empty message

Revision ID: b1dd3e77ee0f
Revises: 813aa213bc95
Create Date: 2023-06-26 13:48:32.037776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b1dd3e77ee0f"
down_revision = "813aa213bc95"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("model_identifier", sa.String(length=255), nullable=False),
        sa.Column("duration", sa.DECIMAL(), nullable=False),
        sa.Column("peak_memory", sa.DECIMAL(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("hyperparameters", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("training_statistics")
    # ### end Alembic commands ###
