"""empty message

Revision ID: c0fc8eda307a
Revises: 19f3cec5576d
Create Date: 2023-08-28 09:39:27.367937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c0fc8eda307a"
down_revision = "19f3cec5576d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training_finished", sa.Column("deleted", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "training_started", sa.Column("deleted", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "training_step_finished", sa.Column("deleted", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "training_step_started", sa.Column("deleted", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("training_step_started", "deleted")
    op.drop_column("training_step_finished", "deleted")
    op.drop_column("training_started", "deleted")
    op.drop_column("training_finished", "deleted")
    # ### end Alembic commands ###
