"""empty message

Revision ID: f365dbaf5d6b
Revises: b1dd3e77ee0f
Create Date: 2023-06-26 18:22:50.160469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f365dbaf5d6b"
down_revision = "b1dd3e77ee0f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training_statistics",
        sa.Column("peak_memory_percentage", sa.DECIMAL(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("training_statistics", "peak_memory_percentage")
    # ### end Alembic commands ###
