# Generated by Django 4.0.3 on 2023-05-04 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_remove_cartitem_create_at_remove_cartitem_product_and_more"),
        ("user", "0005_alter_user_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cart",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="cart.cart"
            ),
        ),
    ]
