# Generated by Django 4.0.3 on 2023-07-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_user_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
