# Generated by Django 4.0.3 on 2023-02-15 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country", "0002_currency_pricelist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricelist",
            name="currency",
        ),
    ]
