# Generated by Django 4.0.3 on 2023-02-15 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country", "0003_remove_pricelist_currency"),
        ("product", "0011_pricelist_alter_productprice_price_list"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PriceList",
        ),
    ]
