# Generated by Django 4.0.3 on 2023-02-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country", "0006_country_default_price_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Country", "verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name": "Currency", "verbose_name_plural": "Currencies"},
        ),
        migrations.AlterField(
            model_name="currency",
            name="symbol_position",
            field=models.CharField(
                choices=[("BEFORE", "BEFORE"), ("AFTER", "AFTER")],
                default="AFTER",
                max_length=6,
            ),
        ),
    ]
