# Generated by Django 4.0.3 on 2023-05-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_alter_country_options_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, unique=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'VAT Group',
                'verbose_name_plural': 'VAT Groups',
            },
        ),
    ]
