# Generated by Django 4.0.3 on 2023-05-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_vatgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatgroup',
            name='country',
            field=models.ForeignKey(default='cz', on_delete=django.db.models.deletion.CASCADE, to='country.country'),
            preserve_default=False,
        ),
    ]
