# Generated by Django 4.0.3 on 2023-05-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country", "0010_alter_vatgroup_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vatgroup",
            name="rate",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
