# Generated by Django 4.0.3 on 2023-06-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0017_rename_billingaddress_billinginfo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billinginfo",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="country",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="currency",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shippinginfo",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vatgroup",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
