# Generated by Django 4.0.3 on 2023-05-09 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_paymentmethod_shippingmethod_shippingmethodcountry_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentmethodtranslation",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="shippingmethodtranslation",
            old_name="name",
            new_name="title",
        ),
    ]
