# Generated by Django 4.0.3 on 2023-05-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_rename_name_paymentmethodtranslation_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="payment_method"),
        ),
        migrations.AlterField(
            model_name="shippingmethod",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="shipping_method"),
        ),
    ]
