# Generated by Django 4.0.3 on 2023-05-09 09:58

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_alter_paymentmethod_image_alter_shippingmethod_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=cart.models.get_payment_method_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="shippingmethod",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=cart.models.get_shipping_method_image_path,
            ),
        ),
    ]
