# Generated by Django 4.0.3 on 2023-05-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_alter_paymentmethod_image_alter_shippingmethod_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingmethod",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="shipping_method/"),
        ),
    ]
