# Generated by Django 4.0.3 on 2023-05-09 12:34

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0008_alter_shippingmethod_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingmethod",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=cart.models.get_shipping_method_image_path,
            ),
        ),
    ]
