# Generated by Django 4.0.3 on 2023-05-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_alter_shippingmethod_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentmethodcountry",
            old_name="price_gross",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="shippingmethodcountry",
            old_name="price_gross",
            new_name="price",
        ),
    ]
