# Generated by Django 4.0.3 on 2023-05-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0010_rename_price_gross_paymentmethodcountry_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingmethodcountry",
            name="payment_methods",
            field=models.ManyToManyField(blank=True, to="cart.paymentmethodcountry"),
        ),
    ]
