# Generated by Django 4.0.3 on 2023-05-11 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_rename_shippping_method_country_cart_shipping_method_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
