# Generated by Django 4.0.3 on 2023-05-16 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0018_cartitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
