# Generated by Django 4.0.3 on 2023-05-16 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0018_alter_cart_billing_address_and_more"),
        ("cart", "0019_cartitem_discount"),
    ]

    operations = []
