# Generated by Django 4.0.3 on 2023-05-17 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0021_cart_pricelist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="billing_address",
            new_name="billing_info",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="shipping_address",
            new_name="shipping_info",
        ),
    ]
