# Generated by Django 4.0.3 on 2023-06-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0024_remove_shippingmethodcountry_api_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethodcountry",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shippingmethodcountry",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
