# Generated by Django 4.0.3 on 2023-06-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_paymentmethod_safe_deleted_and_more'),
        ('cart', '0025_rename_unit_price_gross_cartitem_unit_price_incl_vat_and_more'),
    ]

    operations = [
    ]
