# Generated by Django 4.0.3 on 2023-07-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0026_rename_unit_price_gross_cartitem_unit_price_incl_vat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
