"""empty message

Revision ID: 174a0075e044
Revises: 334eb51e6c67
Create Date: 2023-05-07 21:49:07.689473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "174a0075e044"
down_revision = "334eb51e6c67"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "distance", sa.Column("model_identifier", sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("distance", "model_identifier")
    # ### end Alembic commands ###
