"""empty message

Revision ID: 334eb51e6c67
Revises: fb945a1d5b6c
Create Date: 2023-05-03 14:24:23.702027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "334eb51e6c67"
down_revision = "fb945a1d5b6c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("distance", sa.Column("distance", sa.DECIMAL(), nullable=False))
    op.create_index("distance_distance_idx", "distance", ["distance"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("distance_distance_idx", table_name="distance")
    op.drop_column("distance", "distance")
    # ### end Alembic commands ###
