"""empty message

Revision ID: fb945a1d5b6c
Revises: 
Create Date: 2023-05-03 09:30:46.524453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fb945a1d5b6c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "distance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lhs", sa.String(length=255), nullable=False),
        sa.Column("rhs", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("distance")
    # ### end Alembic commands ###
