# Generated by Django 4.0.3 on 2023-04-16 20:58

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_category_create_at_category_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorytranslation",
            name="description_editorjs",
            field=django_editorjs_fields.fields.EditorJsJSONField(
                blank=True,
                help_text="Main product description in given language in EditorJS format",
                null=True,
            ),
        ),
    ]
