# Generated by Django 4.0.3 on 2023-04-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagefrontend',
            name='frontend_path',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
