# Generated by Django 4.0.3 on 2023-04-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_alter_pagecategory_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecategory",
            name="type",
            field=models.ManyToManyField(blank=True, to="cms.pagecategorytype"),
        ),
    ]
