# Generated by Django 4.0.3 on 2023-06-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0005_alter_pagecategory_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecategory",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pagecategorytype",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pagecms",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pagefrontend",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
