# Generated by Django 4.0.3 on 2023-06-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_pagecategory_safe_deleted_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={},
        ),
        migrations.RemoveField(
            model_name="pagecms",
            name="safe_deleted",
        ),
        migrations.RemoveField(
            model_name="pagefrontend",
            name="safe_deleted",
        ),
        migrations.AddField(
            model_name="page",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
