# Generated by Django 4.0.3 on 2023-06-16 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0007_alter_page_options_remove_pagecms_safe_deleted_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveField(
            model_name="page",
            name="safe_deleted",
        ),
    ]
