# Generated by Django 4.0.3 on 2023-06-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0008_alter_page_options_remove_page_safe_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecms",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pagefrontend",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
