# Generated by Django 4.0.3 on 2023-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0009_pagecms_safe_deleted_pagefrontend_safe_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagecms",
            name="safe_deleted",
        ),
        migrations.RemoveField(
            model_name="pagefrontend",
            name="safe_deleted",
        ),
        migrations.AddField(
            model_name="page",
            name="safe_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
