# Generated by Django 4.0.3 on 2022-11-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_variants",
        ),
        migrations.DeleteModel(
            name="ProductVariant",
        ),
    ]
