# Generated by Django 4.0.3 on 2022-11-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_variants',
            field=models.ManyToManyField(blank=True, to='product.productvariant'),
        ),
    ]
