# Generated by Django 4.0.3 on 2023-02-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0003_remove_pricelist_currency"),
        ("product", "0010_productprice_delete_currency_delete_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("rounding", models.BooleanField(default=False)),
                ("includes_vat", models.BooleanField(default=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="country.currency",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="productprice",
            name="price_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.pricelist"
            ),
        ),
    ]
