# Generated by Django 4.0.3 on 2023-02-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_pricelist_alter_productprice_price_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseattribute",
            name="ext_attributes",
            field=models.ManyToManyField(blank=True, to="product.extensionattribute"),
        ),
    ]
