# Generated by Django 4.0.3 on 2023-02-15 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_alter_baseattribute_ext_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="productprice",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productprice",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
