# Generated by Django 4.0.3 on 2023-02-15 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_productprice_create_at_productprice_update_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelist",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricelist",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
