# Generated by Django 4.0.3 on 2023-03-27 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_productmedia_alter_baseattribute_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allowed_attribute_types",
                    models.ManyToManyField(
                        blank=True, null=True, to="product.attributetype"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.producttype",
            ),
        ),
    ]
