# Generated by Django 4.0.3 on 2023-03-13 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_productimage_productvariantimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productprice",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price",
                to="product.productvariant",
            ),
        ),
    ]
