# Generated by Django 4.0.3 on 2023-03-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productmedia_productvariantmedia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariantimage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productvariantimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productvariantimage',
            name='product_variant',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductVariantImage',
        ),
    ]
