# Generated by Django 4.0.3 on 2023-03-15 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_productmedia_productvariantmedia"),
        ("product", "0016_alter_productprice_product_variant"),
    ]

    operations = []
