# Generated by Django 4.0.3 on 2023-03-29 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_productmedia_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_media', to='product.product'),
        ),
    ]
