# Generated by Django 4.0.3 on 2023-03-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0017_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttype",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
