# Generated by Django 4.0.3 on 2023-04-02 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0017_alter_productmedia_product"),
        ("product", "0018_alter_producttype_name"),
    ]

    operations = []
