# Generated by Django 4.0.3 on 2023-03-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0018_alter_productvariantimage_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="attributes",
            field=models.ManyToManyField(
                blank=True, null=True, to="product.baseattribute"
            ),
        ),
    ]
