# Generated by Django 4.0.3 on 2023-04-03 07:34

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_merge_20230402_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='media',
            field=models.ImageField(upload_to=product.models.product_media_upload_path),
        ),
    ]
