# Generated by Django 4.0.3 on 2023-03-16 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0020_alter_productprice_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productprice",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="product_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price",
                to="product.productvariant",
            ),
        ),
    ]
