# Generated by Django 4.0.3 on 2023-04-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0022_alter_attributetype_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseattribute",
            name="value",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
