# Generated by Django 4.0.3 on 2023-05-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0026_pricelist_is_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricelist",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
