# Generated by Django 4.0.3 on 2023-05-04 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0028_productvariant_availability"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariant",
            old_name="availability",
            new_name="stock_quantity",
        ),
    ]
