# Generated by Django 4.0.3 on 2023-05-04 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("country", "0007_alter_country_options_alter_currency_options_and_more"),
        ("product", "0029_rename_availability_productvariant_stock_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTypeVatGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vat", models.IntegerField(default=20)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="country.country",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.producttype",
                    ),
                ),
            ],
        ),
    ]
