# Generated by Django 4.0.3 on 2023-05-04 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0031_alter_producttypevatgroup_product_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricelist",
            name="includes_vat",
        ),
    ]
