# Generated by Django 4.0.3 on 2023-05-04 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_vatgroup'),
        ('product', '0032_remove_pricelist_includes_vat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttypevatgroup',
            name='vat',
        ),
        migrations.AddField(
            model_name='producttypevatgroup',
            name='vat_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.vatgroup'),
        ),
    ]
