# Generated by Django 4.0.3 on 2023-05-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_vatgroup_country'),
        ('product', '0033_remove_producttypevatgroup_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='vat_groups',
            field=models.ManyToManyField(blank=True, related_name='product_types', to='country.vatgroup'),
        ),
        migrations.DeleteModel(
            name='ProductTypeVatGroup',
        ),
    ]
