# Generated by Django 4.0.3 on 2023-05-04 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_producttype_vat_groups_delete_producttypevatgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
