# Generated by Django 4.0.3 on 2023-06-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0041_alter_testmodel_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="testmodel",
            managers=[],
        ),
        migrations.DeleteModel(
            name="TestModelTranslation",
        ),
    ]
