# Generated by Django 4.0.3 on 2023-06-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0043_testmodeltranslation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="testmodeltranslation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="testmodeltranslation",
            name="master",
        ),
        migrations.DeleteModel(
            name="TestModel",
        ),
        migrations.DeleteModel(
            name="TestModelTranslation",
        ),
    ]
