# Generated by Django 4.0.3 on 2023-08-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0047_extattributetype_safe_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="recommendation_weight",
            field=models.FloatField(default=0.5),
        ),
    ]
