"""empty message

Revision ID: 00f11f2be022
Revises: 1b6eebfd0758
Create Date: 2023-06-26 12:09:05.938165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00f11f2be022"
down_revision = "1b6eebfd0758"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_detail_enter",
        sa.Column("model_identifier", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "recommendation_view",
        sa.Column("model_identifier", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recommendation_view", "model_identifier")
    op.drop_column("product_detail_enter", "model_identifier")
    # ### end Alembic commands ###
