"""empty message

Revision ID: 0dd2dc7bcbd7
Revises: 704a0ff63aad
Create Date: 2023-06-03 15:25:59.350290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0dd2dc7bcbd7"
down_revision = "704a0ff63aad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "product_detail_enter_session_id_idx",
        "product_detail_enter",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "product_detail_enter_session_id_idx", table_name="product_detail_enter"
    )
    # ### end Alembic commands ###
