"""empty message

Revision ID: 14cacbe2751a
Revises: 61283a295aa9
Create Date: 2023-06-28 22:33:44.495804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "14cacbe2751a"
down_revision = "61283a295aa9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prediction_result",
        sa.Column("recommendation_type", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "product_detail_enter",
        sa.Column("model_name", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_detail_enter", "model_name")
    op.drop_column("prediction_result", "recommendation_type")
    # ### end Alembic commands ###
