"""empty message

Revision ID: 1b6eebfd0758
Revises: 89ffdd8fccd9
Create Date: 2023-06-20 14:22:29.726703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1b6eebfd0758"
down_revision = "89ffdd8fccd9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "session",
        sa.Column(
            "visited_product_variants",
            postgresql.ARRAY(sa.String(length=255)),
            nullable=True,
        ),
    )
    op.execute(
        "UPDATE session SET visited_product_variants = array[]::text[] WHERE visited_product_variants is NULL"
    )
    op.alter_column(
        "session",
        "visited_product_variants",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session", "visited_product_variants")
    # ### end Alembic commands ###
