"""empty message

Revision ID: 846849832ccd
Revises: 2ecf45faba79
Create Date: 2023-07-18 11:07:18.937224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "846849832ccd"
down_revision = "2ecf45faba79"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prediction_result", sa.Column("deleted", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE prediction_result SET deleted = false WHERE deleted is NULL")
    op.alter_column("prediction_result", "deleted", nullable=False)

    op.add_column(
        "product_add_to_cart", sa.Column("deleted", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE product_add_to_cart SET deleted = false WHERE deleted is NULL")
    op.alter_column("product_add_to_cart", "deleted", nullable=False)

    op.add_column(
        "product_detail_enter", sa.Column("deleted", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE product_detail_enter SET deleted = false WHERE deleted is NULL")
    op.alter_column("product_detail_enter", "deleted", nullable=False)

    op.add_column(
        "product_detail_leave", sa.Column("deleted", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE product_detail_leave SET deleted = false WHERE deleted is NULL")
    op.alter_column("product_detail_leave", "deleted", nullable=False)

    op.add_column(
        "recommendation_view", sa.Column("deleted", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE recommendation_view SET deleted = false WHERE deleted is NULL")
    op.alter_column("recommendation_view", "deleted", nullable=False)

    op.add_column("review", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.execute("UPDATE review SET deleted = false WHERE deleted is NULL")
    op.alter_column("review", "deleted", nullable=False)

    op.add_column("session", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.execute("UPDATE session SET deleted = false WHERE deleted is NULL")
    op.alter_column("session", "deleted", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session", "deleted")
    op.drop_column("review", "deleted")
    op.drop_column("recommendation_view", "deleted")
    op.drop_column("product_detail_leave", "deleted")
    op.drop_column("product_detail_enter", "deleted")
    op.drop_column("product_add_to_cart", "deleted")
    op.drop_column("prediction_result", "deleted")
    # ### end Alembic commands ###
