"""empty message

Revision ID: 89ffdd8fccd9
Revises: 0dd2dc7bcbd7
Create Date: 2023-06-03 15:27:42.041613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "89ffdd8fccd9"
down_revision = "0dd2dc7bcbd7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "product_detail_enter_create_at_idx",
        "product_detail_enter",
        ["create_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "product_detail_enter_create_at_idx", table_name="product_detail_enter"
    )
    # ### end Alembic commands ###
