"""empty message

Revision ID: 9109778cfa26
Revises: 00f11f2be022
Create Date: 2023-06-26 13:27:10.282035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9109778cfa26"
down_revision = "00f11f2be022"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE recommendation_view SET model_identifier = '' WHERE model_identifier is NULL"
    )
    op.alter_column(
        "recommendation_view",
        "model_identifier",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recommendation_view",
        "model_identifier",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###
