"""empty message

Revision ID: af2767c85a4c
Revises: 9134449c5629
Create Date: 2023-04-17 00:11:41.279376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af2767c85a4c"
down_revision = "9134449c5629"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_add_to_cart",
        sa.Column("product_variant_sku", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "product_detail_enter",
        sa.Column("product_variant_sku", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "product_detail_leave",
        sa.Column("product_variant_sku", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "recommendation_view",
        sa.Column("product_variant_sku", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "review", sa.Column("product_variant_sku", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review", "product_variant_sku")
    op.drop_column("recommendation_view", "product_variant_sku")
    op.drop_column("product_detail_leave", "product_variant_sku")
    op.drop_column("product_detail_enter", "product_variant_sku")
    op.drop_column("product_add_to_cart", "product_variant_sku")
    # ### end Alembic commands ###
