# Generated by Django 4.0.3 on 2023-05-15 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_id",
            new_name="token",
        ),
    ]
