# Generated by Django 4.0.3 on 2023-07-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_rename_unit_price_gross_cartitem_unit_price_incl_vat_and_more'),
        ('order', '0007_orderitemcomplaint_delete_orderitemclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemcomplaint',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='cart.cartitem'),
        ),
    ]
