# Generated by Django 4.0.3 on 2022-10-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
