"""empty message

Revision ID: e1aea32efeb2
Revises: 
Create Date: 2023-04-04 23:04:20.813284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e1aea32efeb2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attribute_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type_name", sa.String(length=200), nullable=True),
        sa.Column("unit", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("update_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("create_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attribute",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("attribute_type_id", sa.Integer(), nullable=True),
        sa.Column("parent_attribute_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["attribute_type_id"],
            ["attribute_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_attribute_id"],
            ["attribute.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attribute_type_product_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attribute_type_id", sa.Integer(), nullable=True),
        sa.Column("product_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["attribute_type_id"],
            ["attribute_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["product_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("update_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("create_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("product_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["product_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_translation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("language_code", sa.String(length=10), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("meta_title", sa.String(length=200), nullable=True),
        sa.Column("meta_description", sa.String(), nullable=True),
        sa.Column("short_description", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("slug", sa.String(length=200), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_variant",
        sa.Column("sku", sa.String(length=255), nullable=False),
        sa.Column("ean", sa.String(length=13), nullable=True),
        sa.Column("weight", sa.DECIMAL(), nullable=True),
        sa.Column("update_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("create_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("sku"),
    )
    op.create_table(
        "attribute_product_variant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attribute_id", sa.Integer(), nullable=True),
        sa.Column("product_variant_sku", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attribute.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_variant_sku"],
            ["product_variant.sku"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_product_variant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("product_variant_sku", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_variant_sku"],
            ["product_variant.sku"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_product_variant")
    op.drop_table("attribute_product_variant")
    op.drop_table("product_variant")
    op.drop_table("product_translation")
    op.drop_table("product")
    op.drop_table("attribute_type_product_type")
    op.drop_table("attribute")
    op.drop_table("product_type")
    op.drop_table("attribute_type")
    # ### end Alembic commands ###
