source 'https://rubygems.org'

gem 'jekyll', '3.9.3'

group :jekyll_plugins do
  gem 'jekyll-feed', '0.15.1'
  gem 'jekyll-seo-tag', '2.8.0'
  gem 'jekyll-sitemap', '1.4.0'
end

gem "webrick", "~> 1.8"
gem "kramdown-parser-gfm"

gem "tzinfo", "~> 2.0", platforms: [:mingw, :mswin, :x64_mingw]
gem "tzinfo-data", "~> 1.2023", platforms: [:mingw, :mswin, :x64_mingw]
