version: "3.9"

services:
  backend:
      container_name: backend
      build: ./backend
      volumes:
        - ./backend/core:/usr/src/app/
      ports:
        - 8000:8000
      env_file:
        - ./backend/docker-compose.env
  frontend_dashboard:
      container_name: dashboard
      build: ./dashboard
      environment:
        CHOKIDAR_USEPOLLING: "true" # https://stackoverflow.com/questions/61576659/how-to-hot-reload-in-reactjs-docker
      volumes:
        - ./dashboard/src:/usr/src/app/src
        - ./dashboard/public:/usr/src/app/public
      ports:
        - 3030:3000
      depends_on:
        - backend
  frontend_storefront:
      container_name: storefront
      build: ./storefront
      environment:
        CHOKIDAR_USEPOLLING: "true" # https://stackoverflow.com/questions/61576659/how-to-hot-reload-in-reactjs-docker
      volumes:
        - ./storefront/src:/usr/src/app/src
        - ./storefront/public:/usr/src/app/public
      ports:
        - 3031:3000
      depends_on:
        - backend