version: "3.9"

services:
  db:
    image: postgres:13.0-alpine
    container_name: db
    volumes:
      - ./recommender_system/setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql
    ports:
      - 5432:5432
    env_file:
      - ./recommender_system/docker-compose.env
