version: "3.9"

services:
  backend:
      build: ./backend
      volumes:
        - ./backend/core:/usr/src/app/
      ports:
        - 8000:8000
      env_file:
        - ./backend/docker-compose.env